// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "SwiftTestHarness",
    platforms: [
        .macOS(.v14)
    ],
    dependencies: [
        .package(name: "RustlsPkiTypes", path: "../build/SPMPackage/macosArm64/Debug")
    ],
    targets: [
        .executableTarget(
            name: "SwiftTestHarnessTests",
            dependencies: [
                .product(name: "RustlsPkiTypesLibrary", package: "RustlsPkiTypes")
            ],
            path: "Tests/SwiftTestHarnessTests",
            linkerSettings: [
                // The SPM package generated by Kotlin's embedSwiftExportForXcode
                // task contains Swift wrapper sources and C bridge declarations,
                // but the actual symbol implementations
                // (`__root____getExceptionMessage__...`) live in
                // `libRustlsPkiTypes.a` produced by the
                // `linkSwiftExportBinaryDebugStaticMacosArm64` /
                // `mergeMacosDebugSwiftExportLibraries` chain. Xcode wires
                // that archive into its own link step via
                // BUILT_PRODUCTS_DIR; a standalone `swift run` invocation
                // has to point at it explicitly. The archive lands at
                // `<repo>/build/swift-test/libRustlsPkiTypes.a` when the
                // embed task runs with the macOS Xcode-style environment
                // variables (see .github/workflows/swift.yml).
                .unsafeFlags([
                    "-L", "../build/swift-test",
                    "-lRustlsPkiTypes",
                ]),
            ]
        ),
    ]
)
